name: text_gradiate

description: |
  A Flutter package for creating gradient text in an easy way.
  This package allows you to add gradient effects to text in your Flutter app effortlessly.

version: 1.0.0

homepage: https://github.com/Ruban-07/text_gradiate

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # The following line ensures that the package is always compatible with the latest stable Flutter release.
  uses-material-design: true

  assets:
    - assets/images/samp1.jpg
    - assets/images/samp2.jpg
    - assets/images/samp3.jpg
